#!/usr/bin/env bash
# Install cmms-api on a Debian box as a systemd service bound to 127.0.0.1.
#
# Usage (on the target Debian machine, as root):
#   sudo CMMS_DB_PATH=/var/lib/cmms/cmms.db \
#        bash scripts/install.sh
#
# The script generates two random tokens and writes them to /etc/cmms-api.env
# (same format as .env.example). Bun loads .env from the working directory;
# systemd loads it via EnvironmentFile. Both paths point at the same file.
#
# To override tokens or port, set them before running:
#   sudo CMMS_API_TOKEN_READ=abc123 PORT=9000 bash scripts/install.sh

set -euo pipefail

# 0. ensure basic tools exist
if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
  echo "==> installing curl (needed for Bun + cloudflared)"
  apt-get update -qq && apt-get install -y -qq curl >/dev/null 2>&1 || true
fi

SERVICE_USER="cmmsapi"
INSTALL_DIR="/opt/cmms-api"
DATA_DIR="/var/lib/cmms"
ENV_FILE="/etc/cmms-api.env"
SERVICE_FILE="/etc/systemd/system/cmms-api.service"
SYSTEMD_UNIT_NAME="cmms-api.service"
PORT="${PORT:-8787}"
HOST="${HOST:-127.0.0.1}"

CMMS_DB_PATH="${CMMS_DB_PATH:-$DATA_DIR/cmms.db}"
CMMS_READ_TOKEN="${CMMS_API_TOKEN_READ:-$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 32)}"
CMMS_WRITE_TOKEN="${CMMS_API_TOKEN_WRITE:-$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 32)}"

# 1. system user
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --home "$INSTALL_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
fi

# 2. install Bun if missing
if ! command -v bun >/dev/null 2>&1; then
  echo "==> installing Bun"
  curl -fsSL https://bun.sh/install | bash
  # the installer drops it into $HOME/.bun/bin; copy into /usr/local/bin
  cp "$HOME/.bun/bin/bun" /usr/local/bin/bun
  chmod +x /usr/local/bin/bun
fi

# 3. install dir + data dir
install -d -m 0755 "$INSTALL_DIR"
install -d -m 0750 -o "$SERVICE_USER" -g "$SERVICE_USER" "$DATA_DIR"

# 4. copy binary (assumes build/cmms-api relative to the repo root)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
if [ -f "$REPO_DIR/cmms-api" ]; then
  install -m 0755 "$REPO_DIR/cmms-api" "$INSTALL_DIR/cmms-api"
elif [ -f "$REPO_DIR/cmms-api.exe" ]; then
  # built on Windows; copy verbatim
  install -m 0755 "$REPO_DIR/cmms-api.exe" "$INSTALL_DIR/cmms-api.exe"
else
  echo "ERROR: built binary not found at $REPO_DIR/cmms-api"
  echo "Build it first: bun run build"
  exit 1
fi

# 5. place the cmms.db if not already at $CMMS_DB_PATH
if [ ! -f "$CMMS_DB_PATH" ]; then
  if [ -f "$REPO_DIR/cmms.db" ]; then
    echo "==> copying cmms.db to $CMMS_DB_PATH"
    install -m 0640 -o "$SERVICE_USER" -g "$SERVICE_USER" "$REPO_DIR/cmms.db" "$CMMS_DB_PATH"
  else
    echo "ERROR: cmms.db not found at $CMMS_DB_PATH or $REPO_DIR/cmms.db"
    echo "Copy the database there first (or set CMMS_DB_PATH=...)."
    exit 1
  fi
fi

# Ensure the service user can read the DB.
chown "$SERVICE_USER:$SERVICE_USER" "$CMMS_DB_PATH" || true
chmod 0640 "$CMMS_DB_PATH" || true

# 6. env file — same format as .env.example; Bun loads it from the
#    working directory, systemd loads it via EnvironmentFile.
umask 077
cat > "$ENV_FILE" <<EOF
# cmms-api runtime config (generated by install.sh)
# See .env.example for the full list of options.

# Database
CMMS_DB_PATH=$CMMS_DB_PATH

# Server
PORT=$PORT
HOST=$HOST

# Auth (randomly generated; give CMMS_API_TOKEN_READ to kiloclaw)
CMMS_API_TOKEN_READ=$CMMS_READ_TOKEN
CMMS_API_TOKEN_WRITE=$CMMS_WRITE_TOKEN
EOF
chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"
chmod 0600 "$ENV_FILE"

# Symlink so the binary finds .env from its working directory too.
ln -sf "$ENV_FILE" "$INSTALL_DIR/.env" 2>/dev/null || true

# 7. systemd unit for cmms-api
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=cmms-api (read/append API for the kiloclaw cloud agent)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$INSTALL_DIR/cmms-api
Restart=on-failure
RestartSec=5
# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$DATA_DIR
PrivateTmp=true
PrivateDevices=true

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 "$SERVICE_FILE"

# enable + start cmms-api
systemctl daemon-reload
systemctl enable "$SYSTEMD_UNIT_NAME"
systemctl restart "$SYSTEMD_UNIT_NAME"

# 8. install cloudflared if missing
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "==> installing cloudflared"
  if command -v apt >/dev/null 2>&1; then
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
      | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" \
      | tee /etc/apt/sources.list.d/cloudflared.list >/dev/null
    apt-get update -qq && apt-get install -y cloudflared
  else
    echo "WARN: could not auto-install cloudflared (no apt). Install it manually."
  fi
fi

# 9. set up cloudflared quick tunnel as a systemd unit
cat > /etc/systemd/system/cloudflared-cmms.service <<UNIT
[Unit]
Description=Cloudflare tunnel to cmms-api (trycloudflare.com)
After=cmms-api.service network-online.target
Wants=cmms-api.service

[Service]
Type=simple
ExecStart=$(command -v cloudflared || echo /usr/bin/cloudflared) tunnel --no-autoupdate --url http://127.0.0.1:$PORT
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable cloudflared-cmms.service
systemctl restart cloudflared-cmms.service

# 10. wait briefly for first-run ETL to start
sleep 2
if ! systemctl is-active --quiet "$SYSTEMD_UNIT_NAME"; then
  echo "WARNING: $SYSTEMD_UNIT_NAME is not active. Tail of journal:"
  journalctl -u "$SYSTEMD_UNIT_NAME" -n 20 --no-pager || true
  exit 1
fi

# 11. wait for cloudflared to print a URL
TUNNEL_URL=""
for attempt in $(seq 1 30); do
  TUNNEL_URL=$(journalctl -u cloudflared-cmms.service --no-pager -n 200 2>/dev/null \
    | grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' | head -1 || true)
  if [ -n "$TUNNEL_URL" ]; then break; fi
  sleep 1
done

cat <<EOF

============================================================
cmms-api installed and running.

  bind        : http://$HOST:$PORT (loopback only)
  env file    : $ENV_FILE
  systemd unit: $SYSTEMD_UNIT_NAME
  binary      : $INSTALL_DIR/cmms-api
  cmms.db     : $CMMS_DB_PATH

  tunnel unit : cloudflared-cmms.service
  tunnel URL  : ${TUNNEL_URL:-"pending (check: journalctl -u cloudflared-cmms -f)"}

Read token (give this to kiloclaw):
  $CMMS_READ_TOKEN

Write token (keep this private; only humans should log new jobs):
  $CMMS_WRITE_TOKEN

To retrieve the tunnel URL later:
  journalctl -u cloudflared-cmms.service -n 50 | grep -oE 'https://[a-z0-9-]+\\.trycloudflare\\.com' | head -1

To verify locally:
  curl -fsS http://127.0.0.1:$PORT/v1/health
  curl -fsS -H "authorization: Bearer $CMMS_READ_TOKEN" \\
       http://127.0.0.1:$PORT/v1/capabilities | head -c 200

To reach from kiloclaw, give it:
  Base URL: $TUNNEL_URL
  Read token: $CMMS_READ_TOKEN
============================================================
EOF
