// src/lib/followUps.ts
//
// Phase 8 (2026-08-24), brainstorm idea A4 — context-aware follow-up
// chips shown under each agent answer.
//
// Heuristic generator: we look at the FINAL answer text + the
// machine scope (if any) and propose 2-3 short follow-up questions.
// The chips are NOT generated by the LLM — the answer may be 60s
// old by the time the user reads it, and an LLM call here would
// add another 2-3s to the response time. Deterministic beats clever
// for "mutass többet erről a témáról".
//
// The follow-up text is the FULL question — when the user taps the
// chip we submit it as-is. The machine-scope `device` (if any) is
// re-attached by the AskPage's submitQuestion() so the next answer
// is automatically scoped to the same machine.
//
// Each chip's `id` is a stable slug so AskPage can use it as a v-for
// key and so tests can target it directly.

export interface FollowUpChip {
  id: string
  text: string
}

// Hungarian sorszam forms we recognise: B2408001, M-26057, J00001.
// We intentionally match the same shape as the in-text SorszamLink
// renderer so a chip fires whenever the answer names a real ticket.
const SORSZAM_RE = /\b([BMJ]-\d{4,8}|[BMJ]\d{6,8})\b/g

// "ANDRITZ Kft." or "VÁMOSGÉP KFT." — uppercase letters, accents
// allowed, dot at end optional. Matches the customer names in the
// legacy CMMS. False positives are acceptable because every chip
// just submits a question.
const CUSTOMER_RE = /\b([A-ZÁÉÍÓÖŐÚÜŰ][A-ZÁÉÍÓÖŐÚÜŰ0-9 .,'-]{4,40}?(?:KFT|KFt|Kft|RT|Rt|ZRT|Kkt|Bt)\.?)\b/g

// "2024.05.10", "2024-05-10", "2024/05/10", "tavaly", "múlt hónap",
// "utolsó 30 nap" — anything that smells like a date reference.
const DATE_RE = /(\d{4}[./-]\d{1,2}[./-]\d{1,2})|(tavaly|idén|múlt hónap|utolsó \d+ nap|az elmúlt|2024|2025|2026)/i

const GENERIC_FOLLOW_UPS: FollowUpChip[] = [
  { id: 'more-on-this', text: 'Mutass több részletet erről a témáról' },
  { id: 'recent-issues', text: 'Melyek a legutóbbi hasonló esetek?' },
  { id: 'next-actions', text: 'Mit javasolsz, mi legyen a következő lépés?' },
]

/**
 * Generate 2-3 follow-up chips from the answer text + optional
 * machine scope. The first chip is always context-specific (sorszam,
 * customer, or device); the rest are generic enough to be useful on
 * any answer.
 */
export function generateFollowUps(answer: string, device?: string | null): FollowUpChip[] {
  const chips: FollowUpChip[] = []

  // 1. Sorszam-specific chip — "show me this ticket's history"
  const sorszamMatch = SORSZAM_RE.exec(answer)
  SORSZAM_RE.lastIndex = 0
  if (sorszamMatch) {
    const sorszam = sorszamMatch[1]!
    chips.push({ id: `sorszam-${sorszam}`, text: `${sorszam} teljes előzménye` })
  }

  // 2. Customer-specific chip — "more from this customer"
  const customerMatch = CUSTOMER_RE.exec(answer)
  CUSTOMER_RE.lastIndex = 0
  if (customerMatch && !chips.some((c) => c.id.startsWith('customer-'))) {
    const customer = customerMatch[1]!.trim()
    chips.push({ id: `customer-${customer.slice(0, 16)}`, text: `Több jegy ettől az ügyféltől` })
  }

  // 3. Date-window chip — "what about a wider time window"
  if (DATE_RE.test(answer) && !chips.some((c) => c.id.startsWith('date-'))) {
    chips.push({ id: 'date-wider', text: 'Mi volt korábban? (szélesebb időablak)' })
  }
  DATE_RE.lastIndex = 0

  // 4. Device-scope chip — only if a device is selected AND the
  // answer mentions it. Skipped if the answer doesn't reference
  // the device (the user already has the device set; redundant).
  if (device && answer.toLowerCase().includes(device.toLowerCase().slice(0, 6))) {
    chips.push({ id: 'device-status', text: `${device} aktuális állapota most` })
  }

  // 5. Always offer at least one generic chip so the user has
  // something to tap even when nothing concrete was extracted.
  // Cap at 3 chips total — three is the magic number for a
  // single row on mobile.
  for (const g of GENERIC_FOLLOW_UPS) {
    if (chips.length >= 3) break
    if (chips.some((c) => c.id === g.id)) continue
    chips.push(g)
  }

  return chips.slice(0, 3)
}
